# General
FILEPATH_MATCH_EXCLUDE: "help,__,defs.py,commands,example-automation.py,add_monkey_input_prompts,theme.py"

# Prompts
MAIN_PROMPT: "Your role is to read the contents of python files, and without changing anything else whatsoever, convert any docstrings not written in the reST style to be written in the reST style."
MAIN_PROMPT_ULTIMATUM: "Limit your response to the verbatim contents of {the-file}, including all existing code and comments, as well as any docstring alterations to comply with the reST style. Add nothing else, and remove nothing."
OUTPUT_EXAMPLE_PROMPT: "Output should be in the following format with no additional context: [file-contents]"