# General
FILEPATH_MATCH_INCLUDE: "monkey,yaml_helpers.py"
#  FILEPATH_MATCH_EXCLUDE: "help,__,defs.py,commands,example-automation.py,add_monkey_input_prompts,theme.py"

# Context
CONTEXT_FILE_PATH: "ROOT_PATH/stor/context/docstring-context.txt"

# Prompts
MAIN_PROMPT: "Your role is to read the contents of python files, and without changing anything else whatsoever, convert any docstring param and return notations to the correct format."
MAIN_PROMPT_ULTIMATUM: "Limit your response to the verbatim contents of {the-file}, including all existing code and comments, as well as any docstring alterations to comply with your instructions. Add nothing else, and remove nothing."
OUTPUT_EXAMPLE_PROMPT: "Output should be in the following format with no additional context: [file-contents]"


#notate-private-methods-monkey:
#
## General
#FILEPATH_MATCH_EXCLUDE: "help,__,defs.py,commands"
#
## Prompts
#MAIN_PROMPT: "Your role is to read the contents of python files, and without changing anything else whatsoever, add a comment that says 'private method candidate' to any method/function that seems like it probably isn't accessed outside of the file. Do not make 'private method candidate' comments on any method already written as a private method (starting with _). Rather than providing the updated code along with additional context, provide ONLY the updated code, with no alterations aside from the private method comments."
#MAIN_PROMPT_ULTIMATUM: "Limit your response to the verbatim contents of {the-file}, including all existing code and comments, as well as any new 'private method candidate' comments. Add nothing else, and remove nothing."
#OUTPUT_EXAMPLE_PROMPT: "Output should be in the following format with no additional context: [file-contents]"
#
## Output Checks
#OUTPUT_CHECK_PROMPT: 'Is the following the contents of a python file? Respond with only one word: "True" or "False".'
#OUTPUT_TRIES: 3