# A monkey for generating help scripts for `monk` entities.

# General
WORK_PATH: "~/local-git/codemonkeys/codemonkeys/commands"
FILE_TYPES_INCLUDED: ".py"
FILEPATH_MATCH_EXCLUDE: "help.py,__init__.py"
FILE_SELECT_MAX_TOKENS: 6000

# Main Prompts
MAIN_PROMPT: 'Write a python script that prints an appealing summary of {the-file} and its usage via `monk {the-file}`, in the style of documentation for a CLI command. Rather than writing a script using similar functionality as {the-file}, use the provided monk command context and print_t function to generate a script that prints a help summary for {the-file}. When referring to {the-file} as a command, do not include the extension.'
MAIN_PROMPT_ULTIMATUM: 'Return only the contents of a script that prints a helpful summary and usage explanation of {the-file}.'
OUTPUT_EXAMPLE_PROMPT: "Make your output similar to the following, but with as much detail and creativity as necessary to explain the command: ```{cop:~/local-git/metamonkeys/stor/context/self-help-context-file.py}```."

# Output
OUTPUT_PATH: "~/local-git/codemonkeys/codemonkeys/help/commands"
SKIP_EXISTING_OUTPUT_FILES: True