################################################################################################
####  MONKEY MANIFEST  #########################################################################
###
##    The Monkey Manifest houses centralized configuration of Automation profiles (monkeys).
##
##    Undefined props will default based on `monkey-config-defaults.yaml`.
##    To unset a prop, set it to null.
################################################################################################


comment-monkey:

  # General
  WORK_PATH: "~/local-git/codemonkeys/codemonkeys"
  FILE_TYPES_INCLUDED: ".py"
  FILEPATH_MATCH_EXCLUDE: "help,__"
  FILE_SELECT_MAX_TOKENS: 7000
  MAX_TOKENS: 8000
#  CONTEXT_FILE_PATH: "help.py"

  # Prompts
  MAIN_PROMPT: "Please add code comments to document the following file: {the-file}. Use PEP8 style docstrings for functions and classes, and single-line comments for other code. Focus on readability and clarity. Rather than include verbose comments, try to make comments elegant and concise. You may add new comments, new docstrings, and edit existing comments. You may also re-order code, but do not add or remove code. If there is no value to adding/altering comments, return the original file verbatim."
  MAIN_PROMPT_ULTIMATUM: "Limit your response to the verbatim contents of {the-file}, including all existing code and comments, as well as any new or altered comments you add. Do not add comments that are not genuinely helpful."
  OUTPUT_EXAMPLE_PROMPT: "Limit your output strictly to the updated contents of the file, including nothing else, like this: [complete contents of file]"

  # Output
  OUTPUT_PATH: "~/local-git/codemonkeys/codemonkeys"
  OUTPUT_REMOVE_STRINGS: "```python\n,```python,```"

  # Output Checks
  OUTPUT_CHECK_PROMPT: 'Examine the following output and determine if it is limited to the contents of a commented python file. Respond with only one word: "True" or "False".'
  OUTPUT_TRIES: 3

#  COMMIT_STYLE: 'gpt'


notate-private-methods-monkey:

  # General
  WORK_PATH: "~/local-git/codemonkeys/codemonkeys"
  FILE_TYPES_INCLUDED: ".py"
  FILEPATH_MATCH_EXCLUDE: "help,__,defs.py,monkey_config_defaults,commands"
  FILE_SELECT_MAX_TOKENS: 3000
  MAX_TOKENS: 4000
#  CONTEXT_FILE_PATH: "help.py"

  # Prompts
  MAIN_PROMPT: "Your role is to read the contents of python files, and without changing anything else whatsoever, add a comment that says 'private method candidate' to any method/function that seems like it probably isn't accessed outside of the file. Rather than providing the updated code along with additional context, provide ONLY the updated code, with no alterations aside from the private method comments."
  MAIN_PROMPT_ULTIMATUM: "Limit your response to the verbatim contents of {the-file}, including all existing code and comments, as well as any new 'private method candidate' comments. Add nothing else, and remove nothing."
  OUTPUT_EXAMPLE_PROMPT: "Output should be in the following format with no additional context: [file-contents]"

  # Output
  OUTPUT_PATH: "~/local-git/codemonkeys/codemonkeys"
  OUTPUT_REMOVE_STRINGS: "```python\n,```python,```"

  # Output Checks
  OUTPUT_CHECK_PROMPT: 'Examine the following output and determine whether it is commented python code only. Respond with only one word: "True" or "False".'
  OUTPUT_TRIES: 3