################################################################################################
####  MONKEY MANIFEST  #########################################################################
###
##    The Monkey Manifest houses centralized configuration of Automation profiles (monkeys).
##
##    Undefined props will default based on `monkey-config-defaults.yaml`.
##    To unset a prop, set it to null.
################################################################################################


default:

  # General
  WORK_PATH: "~/local-git/codemonkeys/codemonkeys"
  FILE_TYPES_INCLUDED: ".py"
  FILEPATH_MATCH_EXCLUDE: "help,__init__.py"
  FILE_SELECT_MAX_TOKENS: 7000
  MAX_TOKENS: 8000
  CONTEXT_FILE_PATH: "help.py"

  # Prompts
  MAIN_PROMPT: "Please generate code for the following task..."
  CONTEXT_SUMMARY_PROMPT: "Provide a summary of this file..."
  MAIN_PROMPT_ULTIMATUM: "Limit your response to the full contents of a python script, and nothing else."
  OUTPUT_EXAMPLE_PROMPT: "Limit your output strictly to the contents of the file, like this: ```complete contents of file```."

  # Output
  OUTPUT_PATH: "~/local-git/codemonkeys/codemonkeys"
  OUTPUT_REMOVE_STRINGS: "```,```python"

  # Output Checks
  OUTPUT_CHECK_PROMPT: 'Examine the following output and determine if it contains the contents of a python script. Respond with only one word: "True" or "False".'
  OUTPUT_TRIES: 3
